import json, torch,  random

from PIL import Image
from core.prompt_loader import get_system_prompt
from agents.agent_tools import local_editor_node, global_editor_node
from agents.agent_types import AgentState
from langgraph.checkpoint.memory import MemorySaver
from langgraph.graph import StateGraph
from langchain_core.runnables import RunnableConfig

from core.config_loader import ConfigLoader
from core.logger import logger

from utils import wrong_object_class_by_planner

def quality_checker_node(state:AgentState, model_registry):

    original = Image.open(state["previous_image_path"]).convert('RGB')
    edited = Image.open(state["current_image_path"]).convert('RGB')

    if state["intent"] == "local_edit":

        mask = state.get("last_mask", 0)
        #if mask == 0: 
        if (isinstance(mask, int) and mask == 0):
            state["quality_score"] = 1.00
            return state
        
        prompt = state["prompt"]
        scores = model_registry.validator.evaluate_local(
            original,
            edited,
            mask,
            prompt
        )

    else:

        prompt = state["prompt"]
        scores = model_registry.validator.evaluate_global(
            original,
            edited,
            state["depth_original"],
            state["depth_generated"],
            prompt
        )

    state["quality_score"] = float(scores['final'])

    return state

def planner_node(state:AgentState, config: RunnableConfig, model_registry):
    thread_id = config.get("configurable", {}).get("thread_id")
    #logger.info(f'Starting generation in the plannar node for thread_id: {thread_id} for original image {state["original_image_path"]} \
     #           with currently processing the image{state['image_path']} for the user prompt {state['prompt']}')

    logger.info(f"Starting generation in the plannar node for thread_id: {thread_id} for original image {state["original_image_path"]} "
                f"with currently processing the image{state['image_path']} for the user prompt '{state['prompt']}'")
    
    history = "\n".join(state.get("conversation_history", []))
    original = state.get("original_image_path")
    current = state.get("current_image_path", original)
    SYSTEM_PROMPT = get_system_prompt()
    state['seed'] = state.get('seed', 42)
    state['message_index'] = state.get('message_index', 0)
    torch.manual_seed(state['seed'])

    prompt = f"""
        {SYSTEM_PROMPT}

        Context:
        - Original Base Image: {original}
        - Your Current Progress: {current}
        - Past Requests: {history}

        User request: {state['prompt']}
    """

    response = model_registry.llm.invoke(prompt)
    text = response.content
    #print(text)
    try:
        start = text.find("{")
        end = text.rfind("}") + 1
        plan = json.loads(text[start:end])
    except:
        try:
            plan = json.loads(text)
        except:
            plan = {"source": "last_edit", "intent": "global_edit", "global_prompt": state['prompt'], "strength": 0.5}
            logger.info(f'Invalid json output generated by planner for {thread_id} and user prompt {state['prompt']}, so \
                        switching to default plan: {plan}')

 
    source_choice = plan.get("source", "last_edit")
    state["image_path"] = original if source_choice == "original" else current
    state["intent"] = plan.get("intent", "global_edit").lower()
    if state['intent'] == 'local_edit':
        flag, final_prompt = wrong_object_class_by_planner(plan['objects'])
        if flag:
            state["intent"]= "global_edit"
            plan = {"global_promp": final_prompt, "strength": 0.5}

            logger.info(f"The one or more detection labels generated by planner are not in detetable lables "
                        f"for {thread_id} and user prompt {state['prompt']}, so switching to global edit with {plan}")
    state["global_prompt"] = plan.get("global_prompt", "")
    state["objects"] = plan.get("objects", [])
    state["strength"] = plan.get("strength", 0.4)

    state["reply"] = plan.get("reply", "Configuring the edit...")

    print(f"Planner chose source: {source_choice} with intent: {state['intent']} and strength: {state['strength']}")
    logger.info(f'Planner chose source: {source_choice} with intent: {state['intent']} and strength: {state['strength']}')
    print('AI reply: ', state['reply'])
    logger.info(f'AI thinking process: {state['reply']}')
    #print('state', state)
    return state

def update_history_node(state:AgentState, config: RunnableConfig):
    if "conversation_history" not in state: state["conversation_history"] = []
    state["conversation_history"].append(state["prompt"])
    #if state.get('output_image_path'): state['current_image_path'] = state['output_image_path']
    state['retry_count'] = 0
    state['seed']=42
    state['message_index'] = state.get('message_index', 0) +1
    logger.info(f"History has been updated for thread_id:{config.get("configurable", {}).get("thread_id")}"
                f"and message_index: {state['message_index']}")

    logger.info(f'Updated image has been stored at {state['current_image_path']}')
    return state

def retry_logic_node(state: AgentState):
    """
    Increments the retry counter and prepares the state for a re-planning turn.
    """
    retry_count = state.get("retry_count", 0)
    state["retry_count"] = retry_count + 1
    state['seed'] = random.randint(1, 100)
    # Revert current_image_path to previous to ensure we don't build on a failed edit
    state['current_image_path'] = state.get('previous_image_path', state.get('original_image_path'))
    
    #print(f"Retry Logic Node: Incrementing retry count to {state['retry_count']}. Resetting image path.")
    logger.info(f'Retry Logic Node: New generated image has been discarded. Incrementing retry count to {state['retry_count']}')
    return state

def router(state: AgentState):

    if state["intent"] == "local_edit":
        return "local_editor"
    
    return "global_editor"

def quality_router(state: AgentState, config: RunnableConfig):
    """
    Routes to either 'update_history' if quality is met or retries exhausted,
    otherwise routes to the 'retry_logic' node.
    """

    config = ConfigLoader("config/pipeline_config.yaml").get('pipeline')
    QUALITY_THRESHOLD = config['quality_threshold']
    MAX_RETRIES = config['retry_limit']
    
    quality_score = state.get("quality_score", 0)
    retry_count = state.get("retry_count", 0)

    logger.info(f"Quality Router Check: Score = {quality_score:.2f}, Current Retry = {retry_count} for message index:"
                f"{state['message_index']} and thread id: {config.get("configurable", {}).get("thread_id")}")


    if quality_score >= QUALITY_THRESHOLD or retry_count >= MAX_RETRIES:
        return "update_history"

    return "retry_logic"

def retry_logic_node(state: AgentState):
    """
    Increments the retry counter and prepares the state for a re-planning turn.
    """
    retry_count = state.get("retry_count", 0)
    state["retry_count"] = retry_count + 1
    
    # Revert current_image_path to previous to ensure we don't build on a failed edit
    state['current_image_path'] = state.get('previous_image_path', state.get('original_image_path'))
    
    print(f"Retry Logic Node: Incrementing retry count to {state['retry_count']}. Resetting image path.")
    return state

def build_graph(model_registry):

    builder = StateGraph(AgentState)

    # 3. Add all necessary nodes
    from functools import partial
    builder.add_node("planner", partial(planner_node, model_registry=model_registry))
    builder.add_node("local_editor", partial(local_editor_node, model_registry=model_registry) )
    builder.add_node("global_editor", partial(global_editor_node, model_registry=model_registry))
    builder.add_node("quality_checker", partial(quality_checker_node, model_registry=model_registry))
    builder.add_node("update_history", update_history_node)
    builder.add_node("retry_logic", retry_logic_node)

    # 4. Set the entry point
    builder.set_entry_point("planner")
    # 5. Add existing conditional edges from planner to editors
    builder.add_conditional_edges(
        "planner",
        router,
        {
            "local_editor": "local_editor",
            "global_editor": "global_editor",
        }
    )

    # 6. Add regular edges from editors to quality_checker
    builder.add_edge("local_editor", "quality_checker")
    builder.add_edge("global_editor", "quality_checker")

    # 7. Add conditional edge from quality_checker using quality_router
    builder.add_conditional_edges(
        "quality_checker",
        quality_router,
        {
            "retry_logic": "retry_logic",
            "update_history": "update_history",
        }
    )
    builder.add_edge("retry_logic", "planner")
    # 8. Set finish point
    builder.set_finish_point("update_history")

    # 9. Compile the graph
    memory = MemorySaver()
    graph = builder.compile(checkpointer=memory)
    logger.info('Langgraph has been built')

    return graph